### ISSUE TITLE
Do you have a copy of the old lambda that built the static app before CodeDeploy?

### ISSUE THREAD

**Issue by StevenACoffman** [s0enke/serverless-boilerplate#2]
This is super cool. I poked around a bit, but I didn't see the old lambda that used to do the `npm build`, and I'd be interested in seeing that if you've got it lying around somewhere.

**Comment by s0enke** [comment]
yes it's here: https://github.com/s0enke/cloudformation-templates/blob/044c4eff680fd33a638c3da7b634b8053d1d8a44/lambda/handler.js

**Comment by StevenACoffman** [comment]
Thanks!
